[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "word2vec-trainer"
version = "0.1.0"
description = "A PyTorch implementation of Word2Vec for learning and experimentation"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

authors = [
    { name = "Abhishek Biswas", email = "rohan.abiswas@gmail.com" }
]

dependencies = [
    "torch>=2.0",
    "numpy>=1.24",
    "pandas>=2.0",
    "tqdm>=4.64"
]

[project.urls]
Repository = "https://github.com/AbhishekBiswas12/word2vec_trainer"
Issues = "https://github.com/AbhishekBiswas12/word2vec_trainer/issues"

[tool.setuptools.packages.find]
where = ["src"]
